default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.db[:user_name] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: localhost
  encoding: unicode

development:
  <<: *default
  database: questionAppApi_development

test:
  <<: *default
  database: questionAppApi_test

production:
  <<: *default
